### ISSUE TITLE
Examples or high level documentation

### ISSUE THREAD

**Issue by schell** [ryantrinkle/reflex#3]
Hi! Thanks for your work! This looks really interesting. I'm looking for info on how to experiment with reflex in an OpenGL environment. More documentation and examples would be greatly appreciated. I'm guessing reflex can be used outside of a DOM environment and I'd like to explore that. Thanks again!

**Comment by ryantrinkle** [comment]
Thanks for checking it out!  Documentation will be coming as fast as I can manage!

Working with OpenGL would be great; you're absolutely right that Reflex can be used outside of the DOM.  If you'd like to talk about the OpenGL use case in more detail, hit me up by email.

**Comment by schell** [comment]
Great! Will do. I'm listening to the part 2 of your NYC HUG talk.

**Comment by DylanSale** [comment]
I am also interested in how this could work for opengl (games specifically).

**Comment by cies** [comment]
+1 for better "highlevel" docs. The 2-part presentation on YoutTube is awesome, but I prefer a proper README any day (which should certainly link to the presentation).

**Comment by dobesv** [comment]
Putting a link to https://github.com/ryantrinkle/try-reflex from teh main
reflex repo would definitely help, along with links to the other example
repos.

**Comment by schell** [comment]
@ryantrinkle has also started an irc channel #reflex-frp on irc.freenode.net.
:+1:

**Comment by mightybyte** [comment]
We're also starting to keep a collection of reflex-related links at http://www.reddit.com/r/reflexfrp

**Comment by BethAr** [comment]
Example for a temporary Front Page:

## Reflex
### Practical Functional Reactive Programming 

Reflex is a framework for building web applications in Haskell, based on the principles of [Functional Reactive Programming](https://wiki.haskell.org/Functional_Reactive_Programming).

The main documentation is still being created, but you can start with the [Try-Reflex Demo](https://github.com/ryantrinkle/try-reflex), here at GitHub, or by watching Ryan Trinkle's presentation at the NYC HUG: [Part 1](https://www.youtube.com/watch?v=mYvkcskJbc4) / [Part 2](https://www.youtube.com/watch?v=3qfc9XFVo2c)

**Comment by ryantrinkle** [comment]
Thanks for the suggestions, everyone!  I think I've captured everything in the develop branches of reflex, reflex-dom, and try-reflex.  I'll merge it all to master soon.

If you have more documentation ideas/comments, please open a new ticket.
